[package]
name = "chemsolver"
version = "0.1.0"
authors = ["Solomon Ucko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.chemsolver-lib]
path = 'chemsolver-lib'

[[bin]]
name = "chemsolver"
path = "main.rs"
